<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Equipo;

class EquipoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Equipo::create([
            'fua' => 'REMO000001',
            'familia_id' => 9,
            'serie' => '7455814',
            'modelo' => 'XS4344',
            'year' => '2004',
            'descripcion' => 'Remolque agricola',
            'cantidad' => 1,
            'origen' => 'NACIONAL',
            'factura' => '2334',
            'pedimento' => '5544567',
            'fecha_adquisicion' => '2022-01-20',
            'horometro' => 55456,
            'placas' => 'SFC4552',
            'moneda' => 'USD',
            'cotizacion_usd' => 20.10,
            'valor_compra' => 1500,
            'valor_traslado' => 520,
            'valor_importacion' => 300,
            'renta_hora' => 200,
            'renta_dia' => 1000,
            'renta_semana' => 6500,
            'renta_mes' => 22000,
            'comentarios' => 'equipo de prueba',
            'propietario' => 'DM',
            'clave_producto_id' => 1,
            'clave_unidad_id' => 1,
            'activo' => true,
        ]);

        Equipo::create([
            'fua' => 'REMO000002',
            'familia_id' => 9,
            'serie' => '8845114',
            'modelo' => 'XS4340',
            'year' => '2002',
            'descripcion' => 'Remolque agricola',
            'cantidad' => 1,
            'origen' => 'NACIONAL',
            'factura' => '2335',
            'pedimento' => '5544567',
            'fecha_adquisicion' => '2022-01-20',
            'horometro' => 55456,
            'placas' => 'SFC4552',
            'moneda' => 'USD',
            'cotizacion_usd' => 20.10,
            'valor_compra' => 1500,
            'valor_traslado' => 520,
            'valor_importacion' => 300,
            'renta_hora' => 200,
            'renta_dia' => 1000,
            'renta_semana' => 6500,
            'renta_mes' => 22000,
            'comentarios' => 'equipo de prueba',
            'propietario' => 'G3',
            'clave_producto_id' => 1,
            'clave_unidad_id' => 1,
            'activo' => true,
        ]);

        Equipo::create([
            'fua' => 'MONT100007',
            'familia_id' => 8,
            'serie' => '8845114',
            'modelo' => 'XS4340',
            'year' => '2002',
            'descripcion' => 'MONTACARGAS CAT # 4',
            'cantidad' => 1,
            'origen' => 'NACIONAL',
            'factura' => '2335',
            'pedimento' => '5544567',
            'fecha_adquisicion' => '2022-01-20',
            'horometro' => 55456,
            'placas' => 'SFC4552',
            'moneda' => 'USD',
            'cotizacion_usd' => 20.10,
            'valor_compra' => 1500,
            'valor_traslado' => 520,
            'valor_importacion' => 300,
            'renta_hora' => 200,
            'renta_dia' => 1000,
            'renta_semana' => 6500,
            'renta_mes' => 22000,
            'comentarios' => 'equipo de prueba',
            'propietario' => 'DM',
            'clave_producto_id' => 1,
            'clave_unidad_id' => 1,
            'activo' => true,
        ]);

        Equipo::create([
            'fua' => 'MART100001',
            'familia_id' => 4,
            'serie' => '8845114',
            'modelo' => 'XS4340',
            'year' => '2002',
            'descripcion' => 'MARTILLO DEMOLEDOR 10 KG MAKITA',
            'cantidad' => 1,
            'origen' => 'NACIONAL',
            'factura' => '2335',
            'pedimento' => '5544567',
            'fecha_adquisicion' => '2022-01-20',
            'horometro' => 55456,
            'placas' => 'SFC4552',
            'moneda' => 'USD',
            'cotizacion_usd' => 20.10,
            'valor_compra' => 1500,
            'valor_traslado' => 520,
            'valor_importacion' => 300,
            'renta_hora' => 200,
            'renta_dia' => 1000,
            'renta_semana' => 6500,
            'renta_mes' => 22000,
            'comentarios' => 'equipo de prueba',
            'propietario' => 'DM',
            'clave_producto_id' => 1,
            'clave_unidad_id' => 1,
            'activo' => true,
        ]);

        Equipo::create([
            'fua' => 'MART100002',
            'familia_id' => 4,
            'serie' => '8845114',
            'modelo' => 'XS4340',
            'year' => '2002',
            'descripcion' => 'MARTILLO DEMOLEDOR 10 KG MAKITA',
            'cantidad' => 1,
            'origen' => 'NACIONAL',
            'factura' => '2335',
            'pedimento' => '5544567',
            'fecha_adquisicion' => '2022-01-20',
            'horometro' => 55456,
            'placas' => 'SFC4552',
            'moneda' => 'USD',
            'cotizacion_usd' => 20.10,
            'valor_compra' => 1500,
            'valor_traslado' => 520,
            'valor_importacion' => 300,
            'renta_hora' => 200,
            'renta_dia' => 1000,
            'renta_semana' => 6500,
            'renta_mes' => 22000,
            'comentarios' => 'equipo de prueba',
            'propietario' => 'G3',
            'clave_producto_id' => 1,
            'clave_unidad_id' => 1,
            'activo' => true,
        ]);

        Equipo::create([
            'fua' => 'MART100003',
            'familia_id' => 4,
            'serie' => '8845114',
            'modelo' => 'XS4340',
            'year' => '2002',
            'descripcion' => 'MARTILLO ROTATIVO HR2470 (15/16") MAKITA',
            'cantidad' => 1,
            'origen' => 'NACIONAL',
            'factura' => '2335',
            'pedimento' => '5544567',
            'fecha_adquisicion' => '2022-01-20',
            'horometro' => 55456,
            'placas' => 'SFC4552',
            'moneda' => 'USD',
            'cotizacion_usd' => 20.10,
            'valor_compra' => 1500,
            'valor_traslado' => 520,
            'valor_importacion' => 300,
            'renta_hora' => 200,
            'renta_dia' => 1000,
            'renta_semana' => 6500,
            'renta_mes' => 22000,
            'comentarios' => 'equipo de prueba',
            'propietario' => 'G3',
            'clave_producto_id' => 1,
            'clave_unidad_id' => 1,
            'activo' => true,
        ]);

        
    }
}
